### ISSUE TITLE
Version 1.2.0 failed to build in FDroid

### ISSUE THREAD

**Issue by agwells** [agwells/dotdash-keyboard-android#23]
See https://f-droid.org/wiki/page/net.iowaline.dotdash/lastbuild_16

It looks like one of the FDroid maintainers has updated the dotdash metadata file, so maybe that will kick off another attempt to build it? https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/net.iowaline.dotdash.txt

I'll check back on it in a couple of days and see whether it has straightened out on its own.

**Comment by mvdan** [comment]
It's missing the support libraries and there is also a java error:

```
    [javac] /home/vagrant/build/net.iowaline.dotdash/src/net/iowaline/dotdash/AppCompatPreferenceActivityJava.java:35: error: class AppCompatPreferenceActivity is public, should be declared in a file named AppCompatPreferenceActivity.java
    [javac] public abstract class AppCompatPreferenceActivity extends PreferenceActivity {
```

**Comment by agwells** [comment]
Cheers, I'll see if I can straighten that out. It's building successfully on my computer (using Eclipse ADT) but perhaps there's some cacheing or something going on there.

**Comment by mvdan** [comment]
Try with Ant, that's what we use. It's the cmdline equivalent of Eclipse.

**Comment by agwells** [comment]
Okay, I've pushed a new version, 1.2.1, which builds successfully with ant.

**Comment by agwells** [comment]
And now version 1.2.1 is up in the FDroid repo.
