### ISSUE TITLE
add local morse code

### ISSUE THREAD

**Issue by kompowiec** [agwells/dotdash-keyboard-android#25]
For example polish:

```
ą  • — • —
ć  — • — • •
ę  • • — • •
é  • • — • •
ch  — — — —
ł  • — • • —
ń  — — • — —
ó  — — — •
ś  • • • — • • •
ż  — — • • — •
ź  — — • • —
```
german

```
À, Å  · − − · −
Ä · − · −
È · − · · −
É · · − · ·
Ö (OE)  − − − ·
Ü · · − −
ß (SZ) · · · − − · ·
CH − − − −
Ñ − − · − −
```

IMO nice to have write in your native language correctly. It's somewhere file which is responsible for mapping keys? I could try request.

**Comment by kompowiec** [comment]
merged #26

**Comment by fedde-s** [comment]
Is this the same issue that has been backlogged in https://github.com/agwells/dotdash-keyboard-android/issues/18?

**Comment by kompowiec** [comment]
right, simply not noticed, closed.
